# Generated by Django 4.0.4 on 2022-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='media',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
