# Generated by Django 4.0.4 on 2022-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contact_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='media',
            field=models.ImageField(blank=True, upload_to='media/%Y%m%d'),
        ),
    ]
